### ISSUE TITLE
Access to raw data

### ISSUE THREAD

**Issue by alexbw** [nicholas-leonard/dp#109]
Hey, thanks for putting this package together, there's a lot of features here.

I'm a relative newcomer to Lua and Torch, so perhaps I'm just being thick, but I'm unable to tell where the actual raw data sits inside of the DataSet. If I want to get at the raw torch tensors, how is this done?

**Comment by nicholas-leonard** [comment]
Yeah it is heavily encapsulated. In most cases :
```lua
ds = dp.SomeDataSource()
ds:[trainSet,validSet,testSet]():[inputs,targets]():[input()]
```
The `trainSet,validSet and testSet` are dp.BaseSet instances.
The `inputs,targets` are dp.View instances.
The `input()` returns the raw input (torch.Tensor) of the dp.View. You could also request a specific type and axis order (view) by calling for example `forward('bchw', 'torch.FloatTensor')`.

For BillionWords the inputs/targets methods won't work because they have a special storage format (for efficiency).

**Comment by alexbw** [comment]
Great, thanks, I'll dig into this more. Out of curiosity, what led you more towards this encapsulated format, instead of something "leaner" like https://github.com/rosejn/torch-datasets?

**Comment by nicholas-leonard** [comment]
Yeah... I don't like it either. But there are tons of reasons for its current format. By design, it provides for greater modularization and flexibility, at the cost of some pollution of the object space. Be we could add a function to call the final tensor using a dp.DataSource method like say,
```lua
get('train', 'input', 'bchw', 'float')
```

And we don't have a `get` without a `set`:
```
set('test', 'target', 'b', tensor)
```
Thanks for bringing this up.

**Comment by nicholas-leonard** [comment]
Thanks again for bringing this up.
https://github.com/nicholas-leonard/dp/blob/master/doc/data.md#dp.DataSource.get
