### ISSUE TITLE
Do you have to use SGD?

### ISSUE THREAD

**Issue by jsuit** [nicholas-leonard/dp#133]
If you use the dp package, are you forced to use SGD? Secondly, are you forced to use a vanilla SGD? E.g., can use rmsprop?

**Comment by nicholas-leonard** [comment]
Hi @jsuit . I am just finalizing the dpnn branch which will be merged to dp this week. With that branch, you can use a `callback` function (see [this example](https://github.com/nicholas-leonard/dp/blob/dpnn/examples/neuralnetwork.lua#L94))  instead of a dp.Visitor like dp.Learn (which is basically SGD). So you could definitely implement RMSPROP. You could even add it as a Module method to [dpnn](https://github.com/nicholas-leonard/dpnn/blob/master/Module.lua).
