### ISSUE TITLE
class hierarchy and file hierarchy inconsistent

### ISSUE THREAD

**Issue by hughperkins** [nicholas-leonard/dp#174]
class hierarchy and file hierarchy inconsistent.

so, for example, `dp.PennTreeBank`, is not in a file `/PennTreeBank.lua`, at the root of the `dp` file hierarchy, but in a subfolder `/data`, and in a file named `penntreebank.lua`.  This makes browsing around the library a lot more effort than if for example the import was for example `dp.data.penntreebank` (or if the files were moved to the root, and renamed to match their imports)

**Comment by nicholas-leonard** [comment]
@hughperkins Yeah the files in data need to be reorganized. I am sorry for the confusion. As for `dp.data.pentreebank`, I prefer to follow torch in making all classes accessible from the root of the package. But maybe I could refactor the data directory into its own repository/package... Not sure yet. 

All I know is that I need to make a major revision to of the DataSource and DataSet classes. I need to remove the archaic DataView object which isn't useful anymore and just adds another layer of complexity. I also need to make the DataSource/Set interface more general and easy to use. But it's kind of hard (for me anyway) because of the need to support so many different use cases.
