### ISSUE TITLE
A question on SentenceSet and RandomSampler

### ISSUE THREAD

**Issue by NorThanapon** [nicholas-leonard/dp#186]
I looked into the [RandomSampler](https://github.com/nicholas-leonard/dp/blob/4616f3a2eca5be0cf1500afe5a0a156e277a9c53/sampler/randomsampler.lua) on  [BillionWords](https://github.com/nicholas-leonard/dp/blob/4616f3a2eca5be0cf1500afe5a0a156e277a9c53/data/billionwords.lua). The sampler calls  ```SentenceSet:sample()``` which randomly selects from data. The next batch is also randomly selected instead of continuing from the previous one. How does a propagator maintain the state of any sequence model? The batch does not necessarily start with ```start_id```. In addition, the model does not continuously forward to then end of sentence.

**Comment by nicholas-leonard** [comment]
@NorThanapon Yeah you are right that it is ugly. Which is why I have begun to move away from SentenceSet, and use TextSet instead. In the example, the RandomSampler + BillionWords (i.e. SentenceSet) has the model forget after each batch : https://github.com/nicholas-leonard/dp/blob/master/examples/recurrentlanguagemodel.lua#L243 . So it works, but it is ugly.
